# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    yarn cache clean
  displayName: 'yarn cache clean'

- script: |
    yarn install
  displayName: 'Yarn install'

- script: |
    yarn lint
  displayName: 'Yarn lint'

- script: |
    CI=true yarn test
  displayName: 'Yarn run tests'

- script: |
    CI=true yarn test-cypress-with-test-api
  displayName: 'Yarn run cypress (e2e) tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/cypress/videos'
    ArtifactName: 'drop'
    publishLocation: 'Container'
